version: '3.4'

services:
#  prometheus:
#    image: ubuntu/prometheus
#    container_name: prometheus
#    ports:
#      - "30090:9090"
#    environment:
#      - TZ=Asia/Kolkata
#    volumes:
#      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml
#
#  grafana:
#    image: grafana/grafana
#    container_name: Grafana
#    ports:
#      - "30091:3000"
#    volumes:
#      - ./grafana-data/data:/var/lib/grafana
      
  sharecodeapi:
    image: alenalex/sharecode-api:master
    restart: always
    environment:
      - ASPNETCORE_URLS=http://*:80
    volumes:
      - /home/share-code-develop/appsettings.json:/app/appsettings.json
      - /home/share-code-develop/snippet-store/:/app/snippet-store/
      - /home/share-code-develop/Logs/:/app/Logs/    
    ports:
      - "45012:80"