name: .NET 8 CI/CD Pipeline for Sharecode.Backend.Api on ARM64

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0' # Set to .NET 8

    - name: Restore Dependencies
      run: dotnet restore Sharecode.Backend.Api/Sharecode.Backend.Api.csproj

    - name: Build with dotnet
      run: dotnet build Sharecode.Backend.Api/Sharecode.Backend.Api.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish Sharecode.Backend.Api/Sharecode.Backend.Api.csproj -c Release -o out/Sharecode.Backend.Api

    # Set up QEMU and Docker Buildx for ARM64 architecture
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Sharecode.Backend.Api/Dockerfile
        push: true
        tags: alenalex/sharecode-api:master
        platforms: linux/arm64

    - name: Deploy to VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.VM_PASSWORD }}
        script: |
          docker pull alenalex/sharecode-api:master
          docker stop sharecode-backend-api || true
          docker rm sharecode-backend-api || true
          docker run -d --name sharecode-backend-api -p 80:80 alenalex/sharecode-api:master
