name: Build and deploy Worker DbCleanup
on:
  push:
    branches: [ master ]


jobs:
  check-for-worker-db-cleanup:
    runs-on: ubuntu-latest
    outputs:
      state: $ {{ steps.noChangeStep.outputs.state }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed files
        id: change-files-worker-db-cleanup
        uses: tj-actions/changed-files@v41
        with:
          files: 'Sharecode.Backend.Worker.DbCleanup/**'

      - name: Success file(s) changed
        if: steps.change-files-worker-db-cleanup.outputs.any_changed == 'true'
        run: echo Changes detected in DbCleanUp worker. This will be build and deployed

      - name: Success file(s) no change
        id: noChangeStep
        if: steps.change-files-worker-db-cleanup.outputs.any_changed != 'true'
        run: |
          exit 1
          
  build-and-push-job-worker-db-cleanup:
    needs: [check-for-worker-db-cleanup]
    runs-on: self-hosted
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET 8
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'

      - name: Restore Dependencies for Job
        run: dotnet restore Sharecode.Backend.Worker.DbCleanup/Sharecode.Backend.Worker.DbCleanup.csproj

      - name: Build Job with dotnet
        run: dotnet build Sharecode.Backend.Worker.DbCleanup/Sharecode.Backend.Worker.DbCleanup.csproj --configuration Release --no-restore

      - name: Publish Job
        run: dotnet publish Sharecode.Backend.Worker.DbCleanup/Sharecode.Backend.Worker.DbCleanup.csproj -c Release -o out/Sharecode.Backend.Worker.DbCleanup

      - name: Build Job Docker Image
        run: |
          docker build -t alenalex/sharecode-worker-dbcleanup:master -f Sharecode.Backend.Worker.DbCleanup/Dockerfile .
      - name: Docker Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        if: github.ref == 'refs/heads/master'

      - name: Push Docker Image
        run: |
          docker push alenalex/sharecode-worker-dbcleanup:master
        if: github.ref == 'refs/heads/master'      
          
  deploy:
    needs: [
      build-and-push-job-worker-db-cleanup
    ]
    
    runs-on: self-hosted
    
    steps:
      - name: Update docker compose from Github
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          source: "docker-compose.yml"
          target: "/home/share-code-develop/"

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            cd /home/share-code-develop
            docker compose pull sharecode-dbcleanup-job
            docker compose up -d sharecode-dbcleanup-job    