name: Build and deploy .NET 
on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0' # Set to .NET 8

    - name: Restore Dependencies
      run: dotnet restore Sharecode.Backend.Api/Sharecode.Backend.Api.csproj

    - name: Build with dotnet
      run: dotnet build Sharecode.Backend.Api/Sharecode.Backend.Api.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish Sharecode.Backend.Api/Sharecode.Backend.Api.csproj -c Release -o out/Sharecode.Backend.Api

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Sharecode.Backend.Api/Dockerfile
        push: true
        tags: alenalex/sharecode-api:master
        platforms: linux/amd64,linux/arm64

    - name: Deploy to VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.VM_PASSWORD }}
        script: |
          docker pull alenalex/sharecode-api:master

          # Check if the container is running and stop it
          if [ $(docker ps -q -f name=sharecode-api) ]; then
              echo "Stopping running container sharecode-api"
              docker stop sharecode-api
          else
              echo "No running container named sharecode-api found."
          fi

          # Check if the container exists and remove it
          if [ $(docker ps -a -q -f name=sharecode-api) ]; then
              echo "Removing existing container sharecode-api"
              docker rm sharecode-api
          else
              echo "No container named sharecode-api to remove."
          fi

          # Run the new container
          echo "Running new container sharecode-backend-api"
          docker run -d --name sharecode-backend-api -p 45012:80 alenalex/sharecode-api:master
