name: Build and deploy .NET 
on:
  push:
    branches: [ master ]


jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up .NET 8
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Inject the latest email-templates
      run: |
        git clone –single-branch --branch master https://github.com/Share-Code-Development/Email-templates.git email-templates
        cp -r email-templates Sharecode.Backend.Api/email-templates

    - name: Restore Dependencies
      run: dotnet restore Sharecode.Backend.Api/Sharecode.Backend.Api.csproj

    - name: Build with dotnet
      run: dotnet build Sharecode.Backend.Api/Sharecode.Backend.Api.csproj --configuration Release --no-restore
      
    - name: Run Code Quality Tests
      run: dotnet test Sharecode.Backend.UnitTest.CodeQuality/Sharecode.Backend.UnitTest.CodeQuality.csproj      

    - name: Publish
      run: dotnet publish Sharecode.Backend.Api/Sharecode.Backend.Api.csproj -c Release -o out/Sharecode.Backend.Api

    - name: Build Docker Image
      run: |
        docker build -t alenalex/sharecode-api:master -f Sharecode.Backend.Api/Dockerfile .
    - name: Docker Login
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      if: github.ref == 'refs/heads/master'

    - name: Push Docker Image
      run: |
        docker push alenalex/sharecode-api:master
      if: github.ref == 'refs/heads/master'

    - name: Deploy to VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.VM_PASSWORD }}
        script: |
          docker pull alenalex/sharecode-api:master
          docker stop sharecode-backend-api || true
          docker rm sharecode-backend-api || true
          docker run -d --name sharecode-backend-api -e ${{ secrets.DEV_ENV }} -v ${{ secrets.DEV_CONFIGURATION }}:/app/appsettings.json -p ${{ secrets.DEV_NETWORK }}:80 alenalex/sharecode-api:master --restart=always
